server:
  port: 8010
# 应用名称（Nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        # ephemeral: false # 永久实例，哪怕宕机了也不会删除
        # service: 默认取${spring.application.name}，也可以通过配置该项来设置服务名
        # group: DEFAULT_GROUP # 默认取DEFAULT_GROUP，为了做更细的相同特征的服务分组管理
stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: study.springcloud.order.rule.CustomRule
ribbon:
  eager-load:
    # 开启ribbon的立即加载
    enabled: true
    # 配置stock-service使用ribbon立即加载，使用多个逗号进行分隔
    clients: stock-service