server:
  port: 8012
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos